
USE BOOK_STORE;

DELIMITER $$

CREATE  TRIGGER CHECK_NEG_QUANTITY BEFORE UPDATE ON BOOKS FOR EACH ROW
BEGIN
	IF NEW.QUANTITY<0 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='QUANTITY CANNOT BE NEGATIVE';
	END IF;
END$$
DELIMITER ;


DELIMITER $$

CREATE  TRIGGER PLACE_ORDER AFTER UPDATE ON BOOKS FOR EACH ROW
BEGIN
	IF NEW.QUANTITY < OLD.MIN_QUANTITY THEN 
		INSERT INTO BOOK_ORDER(ISBN,QUANTITY,ORDER_DATE) VALUES(NEW.ISBN,2*OLD.MIN_QUANTITY,NOW());
	END IF;
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER CONFIRM_ORDER BEFORE DELETE ON BOOK_ORDER FOR EACH ROW
BEGIN
	UPDATE BOOKS SET QUANTITY = QUANTITY + OLD.QUANTITY 
		WHERE ISBN = OLD.ISBN;
END$$
DELIMITER ;

DELIMITER $$

CREATE TRIGGER BEFORE_SALE BEFORE INSERT ON SALES FOR EACH ROW
BEGIN
	UPDATE BOOKS SET QUANTITY = QUANTITY - NEW.QUANTITY WHERE ISBN = NEW.ISBN;
END$$

DELIMITER ;
